# Generated by Django 3.2.1 on 2021-05-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('memo', 'MEMO'), ('algorithm', 'ALGORITHM'), ('log', 'LOG')], max_length=15)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
