# Generated by Django 3.2.1 on 2021-06-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210531_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('memo', 'MEMO'), ('algorithm', 'ALGORITHM')], max_length=15),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_choices', models.CharField(choices=[('workout', 'WORKOUT'), ('algorithm', 'ALGORITHM'), ('software development', 'SOFTWARE_DEVELOPMENT'), ('reading', 'READING'), ('marketing', 'MARKETING')], max_length=100)),
                ('hours', models.IntegerField(default=1)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.log')),
            ],
        ),
    ]
