# Generated by Django 3.2 on 2021-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='calendar_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='report_period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='ticker',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='updated',
            field=models.CharField(max_length=10),
        ),
    ]
