# Generated by Django 3.2 on 2021-04-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuation',
            name='ticker',
        ),
    ]
