# Generated by Django 3.2 on 2021-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_remove_valuation_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
