# Generated by Django 3.2 on 2021-05-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companymodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
