# Generated by Django 3.2.1 on 2021-05-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowRelation',
        ),
    ]
